data:
  csv_url: "http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"
  csv_columns: ['MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight', 'Acceleration', 'Model Year', 'Origin']
  csv_na_values: ['?']
  csv_comment: '\t'
  csv_sep: ' '
  split_frac: 0.8
  split_random_state: 0
  label_column: 'MPG'
  cat2hot_categories: ['Origin']
  cat2hot_mapping: [['USA', 'Europe', 'Japan']]

model:
  learning_rate: 0.1
  loss_function: 'mean_absolute_error'

train:
  epochs: 100
  validation_split: 0.2
  visualize_loss: False

plot:
  y_lim_bot: 0
  y_lim_top: 10

database:
  name: "ml_metrics.db"
  aggregate: True

tables:
  - name: "Datasets"
    query: |
      CREATE TABLE IF NOT EXISTS Datasets (
          DataSetID INTEGER PRIMARY KEY AUTOINCREMENT,
          DatasetURL TEXT,
          SourceColumns TEXT,
          TargetColumn  TEXT,
          DropNA BOOLEAN,
          OneHotEncoding BOOLEAN,
          SplitFraction REAL,
          SplitRandomState INTEGER
      );
  - name: "Models"
    query: |
        CREATE TABLE IF NOT EXISTS Models (
            ModelID INTEGER PRIMARY KEY AUTOINCREMENT,
            ModelType TEXT,
            Normalization BOOLEAN,
            LossFunction TEXT,
            LearningRate REAL,
            Optimizer TEXT
        );
  - name: "Training"
    query: |
      CREATE TABLE IF NOT EXISTS Training (
          TrainingID INTEGER PRIMARY KEY AUTOINCREMENT,
          DataSetID INTEGER,
          ModelID INTEGER,
          StartTime DATETIME,
          EndTime DATETIME,
          Epochs INTEGER,
          ValidationSplit REAL,
          FinalTrainLoss REAL,
          FinalValidationLoss REAL,
          EvaluationLoss REAL,
          R2Score REAL,
          FOREIGN KEY (DataSetID) REFERENCES Datasets(DataSetID),
          FOREIGN KEY (ModelID) REFERENCES Datasets(ModelID)
      );
